export default {
  turkish: {
    language: "turkish",
    getback: "Geri",
    latestproducts: "Son Ürünler",
    back: "Geri",
    description: "Açıklama",
    price: "Fiyat",
    status: "Stok durumu",
    instock: "Stokta Mevcut",
    outofstock: "Ürün Tükendi",
    qty: "Miktar",
    addtocart: "Sepete Ekle",
    reviews: "Değerlendirmeler",
    noreviews: "Değerlendirme bulunmamaktadır.",
    reviewsubmittedsuccessfully: "Değerlendirmeniz alınmıştır.",
    writeacustomerreview: "Ürün Hakkında Yorum Yap",
    rating: "Değerlendirme",
    poor: "Berbat",
    fair: "İdare eder",
    good: "İyi",
    verygood: "Çok İyi",
    excellent: "Harika",
    signup: "Kayıt Ol",
    name: "İsim",
    email: "Email",
    password: "Şifre",
    confirm: "Şifreyi Onayla",
    account: "Kayıtlı üye misiniz?",
    register: "Kayıt Ol",
    login: "Giriş Yap",
    newcustomer: "Daha Üye Olmadınız mı?",
    search: "Ara",
    advancedsearch: "Gelişmiş Arama",
    cart: "Sepet",
    searchplace: "Ürün Ara..",
  },
  english: {
    language: "english",
    getback: "Get Back",
    latestproducts: "Latest Products",
    back: "Back",
    description: "Description",
    price: "Price",
    status: "Status",
    instock: "In Stock",
    outofstock: "Out of Stock",
    qty: "Qty",
    addtocart: "Add to Cart",
    reviews: "Reviews",
    writeacustomerreview: "Write a Customer Review",
    noreviews: "No Reviews",
    reviewsubmittedsuccessfully: "Review Submitted Successfully",
    rating: "Rating",
    poor: "Poor",
    fair: "Fair",
    good: "Good",
    verygood: "Very Good",
    excellent: "Excellent",
    signup: "Sign Up",
    name: "Name",
    email: "Email Address",
    password: "Password",
    confirm: "Confirm Password",
    account: "Already have and account?",
    register: "Sign Up",
    login: "Sign In",
    newcustomer: "New Customer?",
    search: "Search",
    advancedsearch: "Advanced Search",
    cart: "Cart",
    searchplace: "Search Products..",
  },
};
